interface CurrencyDictionary {
    [key: string]: string;
}

const currencyNames: CurrencyDictionary = {
    // "AED": "United Arab Emirates Dirham",
    // "ALL": "Albanian Lek",
    // "ANG": "Netherlands Antillean Guilder",
    // "ARS": "Argentine Peso",
    // "AUD": "Australian Dollar",
    // "BAM": "Bosnia and Herzegovina Convertible Mark",
    // "BBD": "Barbadian Dollar",
    // "BDT": "Bangladeshi Taka",
    // "BGN": "Bulgarian Lev",
    // "BHD": "Bahraini Dinar",
    // "BMD": "Bermudian Dollar",
    // "BOB": "Bolivian Boliviano",
    // "BRL": "Brazilian Real",
    // "BWP": "Botswana Pula",
    // "BZD": "Belize Dollar",
    "CAD": "Canadian Dollar",
    // "CHF": "Swiss Franc",
    // "CLP": "Chilean Peso",
    "CNY": "Chinese Yuan",
    // "COP": "Colombian Peso",
    // "CRC": "Costa Rican Colón",
    // "CUP": "Cuban Peso",
    // "CZK": "Czech Koruna",
    // "DJF": "Djiboutian Franc",
    // "DKK": "Danish Krone",
    // "DOP": "Dominican Peso",
    // "DZD": "Algerian Dinar",
    // "EGP": "Egyptian Pound",
    // "ETB": "Ethiopian Birr",
    // "EUR": "Euro",
    // "FJD": "Fijian Dollar",
    "GBP": "British Pound Sterling",
    // "GHS": "Ghanaian Cedi",
    // "GMD": "Gambian Dalasi",
    // "GTQ": "Guatemalan Quetzal",
    "HKD": "Hong Kong Dollar",
    // "HNL": "Honduran Lempira",
    // "HTG": "Haitian Gourde",
    // "HUF": "Hungarian Forint",
    // "IDR": "Indonesian Rupiah",
    // "ILS": "Israeli New Shekel",
    // "INR": "Indian Rupee",
    // "IQD": "Iraqi Dinar",
    // "IRR": "Iranian Rial",
    // "ISK": "Icelandic Króna",
    // "JMD": "Jamaican Dollar",
    // "JOD": "Jordanian Dinar",
    "JPY": "Japanese Yen",
    // "KES": "Kenyan Shilling",
    "KRW": "South Korean Won",
    // "KWD": "Kuwaiti Dinar",
    // "KZT": "Kazakhstani Tenge",
    // "LBP": "Lebanese Pound",
    // "LKR": "Sri Lankan Rupee",
    // "MAD": "Moroccan Dirham",
    // "MDL": "Moldovan Leu",
    // "MGA": "Malagasy Ariary",
    // "MKD": "Macedonian Denar",
    // "MMK": "Myanmar Kyat",
    // "MOP": "Macanese Pataca",
    // "MUR": "Mauritian Rupee",
    // "MVR": "Maldivian Rufiyaa",
    // "MWK": "Malawian Kwacha",
    // "MXN": "Mexican Peso",
    // "MYR": "Malaysian Ringgit",
    // "MZN": "Mozambican Metical",
    // "NGN": "Nigerian Naira",
    // "NIO": "Nicaraguan Córdoba",
    // "NOK": "Norwegian Krone",
    // "NZD": "New Zealand Dollar",
    // "OMR": "Omani Rial",
    // "PAB": "Panamanian Balboa",
    // "PEN": "Peruvian Sol",
    // "PGK": "Papua New Guinean Kina",
    // "PHP": "Philippine Peso",
    // "PKR": "Pakistani Rupee",
    // "PLN": "Polish Złoty",
    // "PYG": "Paraguayan Guaraní",
    // "QAR": "Qatari Riyal",
    // "RON": "Romanian Leu",
    // "RSD": "Serbian Dinar",
    // "RUB": "Russian Ruble",
    // "SAR": "Saudi Riyal",
    // "SCR": "Seychellois Rupee",
    // "SEK": "Swedish Krona",
    // "SGD": "Singapore Dollar",
    // "SLL": "Sierra Leonean Leone",
    // "SOS": "Somali Shilling",
    // "SVC": "Salvadoran Colón",
    // "SZL": "Swazi Lilangeni",
    // "THB": "Thai Baht",
    // "TTD": "Trinidad and Tobago Dollar",
    // "TND": "Tunisian Dinar",
    // "TRY": "Turkish Lira",
    "TWD": "New Taiwan Dollar",
    // "TZS": "Tanzanian Shilling",
    // "UAH": "Ukrainian Hryvnia",
    // "UGX": "Ugandan Shilling",
    "USD": "United States Dollar",
    // "UYU": "Uruguayan Peso",
    // "UZS": "Uzbekistani Som",
    // "VES": "Venezuelan Bolívar",
    // "VND": "Vietnamese Đồng",
    // "XAF": "Central African CFA Franc",
    // "XOF": "West African CFA Franc",
    // "XPF": "CFP Franc",
    // "ZAR": "South African Rand",
    // "ZMW": "Zambian Kwacha",
}

export default currencyNames;